-- 코드를 입력하세요

SELECT TITLE, R.BOARD_ID, REPLY_ID, R.WRITER_ID, R.CONTENTS, DATE_FORMAT(R.CREATED_DATE, "%Y-%m-%d") AS CREATED_DATE 
FROM USED_GOODS_BOARD B
JOIN USED_GOODS_REPLY R
USING (BOARD_ID)
WHERE DATE_FORMAT(B.CREATED_DATE, '%y%m') = DATE_FORMAT('2022-10-01', '%y%m')
ORDER BY R.CREATED_DATE, TITLE;
